use std::fs;
use std::path::PathBuf;

fn manifest_file(relative: &str) -> String {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(relative);
    fs::read_to_string(&path).unwrap_or_else(|error| panic!("read {}: {error}", path.display()))
}

#[test]
fn synthetic_sync_peer_transport_is_debug_only_and_exact_gated() {
    let library = manifest_file("src/lib.rs");
    let setup = manifest_file("src/agent_runtime/sync_setup.rs");
    let fixture = manifest_file("src/qc_sync_peer.rs");

    assert!(library.contains("#[cfg(debug_assertions)]\nmod qc_sync_peer;"));
    assert!(setup.contains("#[cfg(debug_assertions)]\n    let qc_transport"));
    for gate in [
        "MAEKON_DEBUG_QC_FIXTURE_CLI",
        "MAEKON_TC_ISOLATED_PROFILE",
        "MAEKON_APP_FLAVOR",
        "MAEKON_DEBUG_QC_SYNC_PEER_FIXTURE",
    ] {
        assert!(fixture.contains(gate), "missing exact fixture gate {gate}");
    }
    assert!(!fixture.contains("TcpStream"));
    assert!(!fixture.contains("UdpSocket"));
    assert!(!fixture.contains("reqwest"));
}

#[test]
fn peer_disconnect_command_is_capability_scoped() {
    let library = manifest_file("src/lib.rs");
    let commands = manifest_file("src/commands/sync.rs");
    let capability = manifest_file("capabilities/default.json");
    let permission = manifest_file("permissions/autogenerated/forget_sync_peer.toml");

    assert!(library.contains("commands::sync::forget_sync_peer"));
    assert!(commands.contains("pub async fn forget_sync_peer"));
    assert!(capability.contains("\"allow-forget-sync-peer\""));
    assert!(permission.contains("commands.allow = [\"forget_sync_peer\"]"));
}
