use std::fs;
use std::path::PathBuf;

fn manifest_file(relative: &str) -> String {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(relative);
    fs::read_to_string(&path).unwrap_or_else(|error| panic!("read {}: {error}", path.display()))
}

#[test]
fn upload_spool_fixture_is_debug_only_exact_gated_and_network_free() {
    let library = manifest_file("src/lib.rs");
    let fixture = manifest_file("src/qc_upload_spool.rs");

    assert!(library
        .contains("#[cfg(all(debug_assertions, feature = \"analysis\"))]\nmod qc_upload_spool;"));
    for gate in [
        "MAEKON_DEBUG_QC_FIXTURE_CLI",
        "MAEKON_TC_ISOLATED_PROFILE",
        "MAEKON_APP_FLAVOR",
        "MAEKON_DEBUG_QC_UPLOAD_SPOOL_FIXTURE",
        "MAEKON_QC_UPLOAD_SPOOL_CONFIRM",
    ] {
        assert!(fixture.contains(gate), "missing exact fixture gate {gate}");
    }
    assert!(fixture.contains("BatchUploader"));
    assert!(fixture.contains("SqliteStorage"));
    assert!(fixture.contains("interrupt-and-reprime"));
    assert!(fixture.contains("matching_events"));
    assert!(!fixture.contains("TcpStream"));
    assert!(!fixture.contains("UdpSocket"));
    assert!(!fixture.contains("reqwest"));
}

#[test]
fn upload_spool_commands_are_capability_scoped_and_release_closed() {
    let library = manifest_file("src/lib.rs");
    let commands = manifest_file("src/commands/qc_upload_spool.rs");
    let capability = manifest_file("capabilities/default.json");
    let status_permission =
        manifest_file("permissions/autogenerated/get_qc_upload_spool_status.toml");
    let step_permission = manifest_file("permissions/autogenerated/run_qc_upload_spool_step.toml");

    assert!(library.contains("commands::qc_upload_spool::get_qc_upload_spool_status"));
    assert!(library.contains("commands::qc_upload_spool::run_qc_upload_spool_step"));
    assert!(commands.contains("#[cfg(not(all(debug_assertions, feature = \"analysis\")))]"));
    assert!(capability.contains("\"allow-get-qc-upload-spool-status\""));
    assert!(capability.contains("\"allow-run-qc-upload-spool-step\""));
    assert!(status_permission.contains("commands.allow = [\"get_qc_upload_spool_status\"]"));
    assert!(step_permission.contains("commands.allow = [\"run_qc_upload_spool_step\"]"));
}
