#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ARTIFACT_DIR="${ROOT_DIR}/artifacts/integrity"
CARGO_CMD="$ROOT_DIR/scripts/cargo-cache.sh"
VET_MODE="${INTEGRITY_VET_MODE:-advisory}"
VET_CHECK_ARGS=(check --locked --no-minimize-exemptions)

mkdir -p "${ARTIFACT_DIR}"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf "Missing required command: %s\n" "$1" >&2
    exit 1
  fi
}

require_cargo_subcommand() {
  if ! "$CARGO_CMD" "$1" --version >/dev/null 2>&1; then
    printf "Missing required cargo subcommand: cargo %s\n" "$1" >&2
    printf "Install: cargo install cargo-%s --locked\n" "$1" >&2
    exit 1
  fi
}

require_cmd cargo

case "$VET_MODE" in
  strict|advisory) ;;
  *)
    printf "Invalid INTEGRITY_VET_MODE: %s (expected strict|advisory)\n" "$VET_MODE" >&2
    exit 1
    ;;
esac

cd "${ROOT_DIR}"

require_cargo_subcommand audit
require_cargo_subcommand deny
require_cargo_subcommand vet
require_cargo_subcommand cyclonedx

"$CARGO_CMD" test -p maekon-core update_integrity_policy
"$CARGO_CMD" test -p maekon-app integrity_guard
"$CARGO_CMD" test -p maekon-app verify_signature_
"$CARGO_CMD" audit
"$CARGO_CMD" deny check licenses advisories sources bans
if [[ "$VET_MODE" == "strict" ]]; then
  "$CARGO_CMD" vet "${VET_CHECK_ARGS[@]}"
else
  if ! "$CARGO_CMD" vet "${VET_CHECK_ARGS[@]}"; then
    printf "[integrity] cargo-vet advisory failed (strict mode remains enforced on push/schedule).\n" >&2
  fi
fi

find "${ROOT_DIR}/crates" -name 'sbom.cdx.json' -delete
"$CARGO_CMD" cyclonedx --format json --override-filename sbom.cdx --manifest-path Cargo.toml

sbom_count=0
while IFS= read -r sbom_path; do
  crate_name="$(basename "$(dirname "${sbom_path}")")"
  cp "${sbom_path}" "${ARTIFACT_DIR}/${crate_name}.sbom.cdx.json"
  sbom_count=$((sbom_count + 1))
done < <(find "${ROOT_DIR}/crates" -name 'sbom.cdx.json' | sort)

if [ "${sbom_count}" -eq 0 ]; then
  printf "No SBOM files were generated by cargo-cyclonedx\n" >&2
  exit 1
fi

printf "Integrity verification completed.\n"
